Repository JeongHaeun3263/random-picker-web-v1, pull requests merged in 2021-11, with the labels that each got.

#5 [RR-33] Spin Implement Function
  src/assets/images/spin_arrow.png
  src/pages/spin/spin.css
  src/pages/spin/spin.jsx
  src/pages/spin/spin_styled_components.js
Labels: needs review

#6 [RP-35] Dice - Create UI
  src/pages/dice/dice.css
  src/pages/dice/dice.jsx
  src/pages/home/home.jsx
  src/pages/spin/spin.jsx
Labels: review done, needs review

#7 [RP-30] Coin - Create UI
  src/App.js
  src/assets/images/coin/coinFlip.png
  src/assets/images/coin/headCoin.png
  src/assets/images/coin/tailCoin.png
  src/pages/coin/coin.css
  src/pages/coin/coin.jsx
Labels: review done
